config/routes.rb
Wiki::Application.routes.draw do
	
	root :to => "pages#index"
	get 'add' => 'pages#new'
	post "pages/create"
	get "*name/add" => "pages#new_sub", :as => :name_add
	get "*name/edit" => "pages#edit", :as => :name_edit
	post "*name/create" => "pages#createSub", :as => :name_create
	put "*name/update" => "pages#update", :as => :name_update
	delete "*name/destroy" => "pages#destroy", :as => :name_delete
	get "*name" => "pages#show", :as => :page
	
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :text, :title
  validates :title, :presence => true,
                    :length => { :minimum => 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController		
	def getListPages
		_subpages = {}
		@pages.each do |page|
			if _subpages[page.page_id] then
				_subpages[page.page_id].push(page)
			else
				_subpages[page.page_id] = [page]
			end
		end
		return _subpages
	end
	
	def new
		@page = Page.new
	end
	
	def new_sub
		@page = Page.new
	end
	
	def index
		@pages = Page.all
		@_subpages = getListPages
		
	end
	
	def show
		@pages = Page.all
		@_subpages = getListPages
		
		@names = params[:name].split("/")
		@page = Page.find_by_name(@names[-1])
		@subpages = Page.where("page_id = ?", @page.id)
		
		@text = @page.text.gsub(/\*\*(.*?)\*\*/){ "<b>" + $1 + '</b>' }
		@text.gsub!(/\\\\(.*?)\\\\/){ "<i>" + $1 + '</i>' }
		@text.gsub!(/\(\((.*?)\s(.*?)\)\)/){ "<a href='#{$1}'>" + $2 + '</a>' }
	end
	
	def edit
		@names = params[:name].split("/")
		@page = Page.find_by_name(@names[-1])
	end
	
	def update
		@names = params[:name].split("/")
		@page = Page.find_by_name(@names[-1])

		if @page.update_attributes(params[:page])
			redirect_to :action => :show, :name => @page.getFullPath(@page.id).reverse.join("/")
		else
			render 'edit'
		end
	end
	
	def destroy
		@names = params[:name].split("/")
		@page = Page.find_by_name(@names[-1])
		@page.destroy

		redirect_to :action => :index
	end
	
	def create
		@page = Page.new(params[:page])
		@page.page = nil
		if @page.save
			redirect_to :action => :show, :name => @page.getFullPath(@page.id).reverse.join("/")
		else
			render 'new'
		end
	end
	
	def createSub
		@page = Page.new(params[:page]) 
		@names = params[:name].split("/")
		@page.page = Page.find_by_name(@names[-1])
		if @page.save
			redirect_to :action => :show, :name => @page.getFullPath(@page.id).reverse.join("/")
		else
			render 'new'
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wiki</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/edit.html.erb
<h1>Editing page</h1>
 
<%= form_for :page, :url => name_update_path, :method => :put do |f| %>
  <% if @page.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@page.errors.count, "error") %> prohibited
        this page from being saved:</h2>
    <ul>
    <% @page.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', :action => :index %>

app/views/pages/index.html.erb
<h1>Listing posts</h1>
 <%= link_to 'Add page', :action => :new %>
 
<ul> 
	<% @pages.each do |page| %>
		<% if not page.page %>
			<li><%= page.title %>
				<p><%= raw page.getsubpages(@_subpages) %></p>
				<%= link_to 'Show', :action => :show, :name => page.getFullPath(page.id).reverse.join("/") %>
				<%= link_to 'edit', :action => :edit, :name => page.getFullPath(page.id).reverse.join("/") %>
				<%= link_to 'delete', { :action => :destroy, :name => page.getFullPath(page.id).reverse.join('/') }, :method => :delete %></li>
			<ul>
			</ul>
		<% end %>
	<% end %>
</ul>

app/views/pages/new.html.erb
<%= form_for :page, :url => { :action => :create } do |f| %>
  <% if @page.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@page.errors.count, "error") %> prohibited
        this page from being saved:</h2>
    <ul>
    <% @page.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', :action => :index %>

app/views/pages/new_sub.html.erb
<p>Add subpage</p>
<%= form_for :page, :url => name_create_path do |f| %>
  <% if @page.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@page.errors.count, "error") %> prohibited
        this page from being saved:</h2>
    <ul>
    <% @page.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', :action => :index %>

app/views/pages/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @page.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= raw @text %>
</p>

<p><%= raw @page.getsubpages(@_subpages) %></p>
<%= link_to 'Add page', name_add_path %><br/>
<%= link_to 'Back', :action => :index %>